### ISSUE TITLE
Error when FoM Goal is reached with AD algorithm

### ISSUE THREAD

**Issue by Ferlemann** [Quantum-OCS/QuOCS#45]
Using the AD algorithm, i get the following error message when the FoM Goal is reached: 

```
Traceback (most recent call last):
  File "x.py", line 103, in <module>
    main(settings_AD)
  File "x.py", line 42, in main
    optimization_obj.execute()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\quocslib\Optimizer.py", line 89, in execute
    self.opt_alg_obj.run()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\quocslib\optimizationalgorithms\ADAlgorithm.py", line 137, in run
    self.inner_run()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\quocslib\optimizationalgorithms\ADAlgorithm.py", line 156, in inner_run
    results = optimize.minimize(f_call,
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\scipy\optimize\_minimize.py", line 696, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\scipy\optimize\_lbfgsb_py.py", line 359, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\scipy\optimize\_differentiable_functions.py", line 285, in fun_and_grad
    self._update_fun()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\scipy\optimize\_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\scipy\optimize\_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\scipy\optimize\_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\quocslib\optimizationalgorithms\ADAlgorithm.py", line 154, in f_call
    return np.array(self.inner_routine_call(x))
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\quocslib\optimizationalgorithms\ADAlgorithm.py", line 114, in inner_routine_call
    FoM = self._routine_call(optimized_control_parameters=optimized_control_parameters, iterations=0)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\quocslib\optimizationalgorithms\OptimizationAlgorithm.py", line 163, in _routine_call
    self.dsm_obj.sc_obj.is_converged = True
AttributeError: 'ADAlgorithm' object has no attribute 'dsm_obj'. Did you mean: 'comm_obj'?
```

**Comment by ThomasReisser90** [comment]
Fixed in Version 0.0.61
